mlsensor_config rewrite using new facilities of alimonitor

diff --git a/bin/mlsensor_config b/bin/mlsensor_config
--- a/bin/mlsensor_config
+++ b/bin/mlsensor_config
@@ -1,14 +1,14 @@
 #!/bin/bash
 
 ##   functions for configurations editing
-myreplace       () { a=$(echo $1 | sed 's/\//\\\//g') ; b=$(echo $2 | sed 's/\//\\\//g') ; cat | sed "s/$a/$b/g" ; }
+myreplace       () { a=$(echo $1 | /bin/sed 's/\//\\\//g') ; b=$(echo $2 | sed 's/\//\\\//g') ; cat | sed "s/$a/$b/g" ; }
 replace_in_file () { cat $1 | myreplace "$2" "$3" > $1.new ; rm -f $1 ; mv $1.new $1 ; }
 
 cfg_set_value () {
 local CFGFILE="$1"
 local KEY="$2"
 local VALUE="$3"
-/bin/sed --follow-symlinks -i "s#^\($KEY\s*=\s*\).*\$#\1$VALUE#" ${CFGFILE}
+/bin/sed --follow-symlinks -i "s#^\(${KEY}\s*=\s*\).*\$#\1${VALUE}#" ${CFGFILE}
 }
 
 help () {
@@ -21,13 +21,11 @@ echo "arg2 = the name of the storage cluster as seen in MonaLisa - ALICE::SOME_N
 
 ## first argument is the configuration file
 TEMPLATE=$1
-[[ -e ${TEMPLATE} ]] && echo "Config template file is : ${TEMPLATE}" || { echo "Could not find configuration template file" && exit; }
+[[ -e ${TEMPLATE} ]] && echo "Config template file is : ${TEMPLATE}" || { echo "Could not find configuration template file"; exit 1; }
 
-CFG="$(/usr/bin/dirname ${TEMPLATE})/$(/bin/basename ${TEMPLATE} .tmp)"
-
+CFG="$(/bin/dirname ${TEMPLATE})/$(/bin/basename ${TEMPLATE} .tmp)"
 /bin/cp ${TEMPLATE} ${CFG}
-
-CFG_PATH=$(readlink -f ${CFG})
+CFG_PATH=$(/bin/readlink -f ${CFG})
 
 ##   CHECK AND ESTABLISH THE SE NAME
 SE_NAME=$2
@@ -39,69 +37,79 @@ SE_NAME=$2
 if [[ -z "${SE_NAME}" ]] && [[ -e /usr/bin/xrdfs ]] ; then
 
     ## have the ports of possible xrootd servers running; to be used to query the servers
-    XRD_PORT=$(ss -ltnp | awk '/xrootd/ { n=split($4,listening,":");print listening[n];}')
+    XRD_PORT=$(ss -ltnp | awk '/xrootd/ { n=split($4,listening,":");print listening[n];}') #'
 
     ## if server port(s) found try each one until SE_NAME is defined (if manager+server first one will be the manager)
-    for PORT in "${XRD_PORT}"; do
-        [[ -z "${SE_NAME}" ]] && SE_NAME=$(/usr/bin/xrdfs localhost:${PORT} query config sitename);
-    done
+    if [[ -n "${XRD_PORT}"  ]]; then
+      for PORT in "${XRD_PORT}"; do
+          [[ -z "${SE_NAME}" ]] && SE_NAME=$(/usr/bin/xrdfs localhost:${PORT} query config sitename);
+      done
+    fi # end check if XRD_port found
 fi
 
-[[ -z "${SE_NAME}" ]] && { echo "SE name is not defined; use it as argument, export ALICEXRD_SE_NAME, or define it the configuration of _RUNNING_ xrootd server" && exit 10; }
+[[ -z "${SE_NAME}" ]] && { echo "SE name is not defined; use it as argument, export ALICEXRD_SE_NAME, or define it the configuration of _RUNNING_ xrootd server" && exit 1; }
 
 echo "Found SE_NAME=${SE_NAME}"
 
+CURLCMD="/usr/bin/curl -m 1 -fsSLk"
+
 ## Get SE info from MonaLisa and check if the SE name is valid
-se_info=$(/usr/bin/curl -fsSLk http://alimonitor.cern.ch/services/se.jsp?se=${SE_NAME})
-[[ "${se_info}" == "null" ]] && { echo "The stated SE name ${SE_NAME} is not found to be valid by MonaLisa" && exit 10; }
+se_info=$(${CURLCMD} "http://alimonitor.cern.ch/services/se.jsp?se=${SE_NAME}&ml_ip=true&resolve=true";)
+[[ -z "${se_info}" ]] && { sleep 1; se_info=$(${CURLCMD} "http://alimonitor.cern.ch/services/se.jsp?se=${SE_NAME}&ml_ip=true&resolve=true";); }
+[[ -z "${se_info}" ]] && { sleep 2; se_info=$(${CURLCMD} "http://alimonitor.cern.ch/services/se.jsp?se=${SE_NAME}&ml_ip=true&resolve=true";); }
+[[ "${se_info}" == "null" ]] || [[ -z "${se_info}" ]] && { echo "The stated SE name ${SE_NAME} is not found - either bad conectivity or wrong SE name" && exit 1; }
 
-MANAGER_HOST_PORT=$(echo "${se_info}" | /bin/awk -F": " '/seioDaemons/ { gsub ("root://","",$2); print $2 }' )
+## Find information about site from ML
+MONALISA_FQDN=$(/bin/awk -F": " '/MLSERVICE_/ {print $2}' <<< "${se_info}" | head -n1) #'
+MONALISA_PORT="8884"
+ML_DEST="${MONALISA_FQDN}:${MONALISA_PORT}"
 
-MANAGERHOST=$(echo "${MANAGER_HOST_PORT}" | /bin/awk -F":" '{print $1}' )
-MANAGERPORT=$(echo "${MANAGER_HOST_PORT}" | /bin/awk -F":" '{print $2}' )
+## get my ip
+MYNET=$(${CURLCMD} "http://alimonitor.cern.ch/services/ip.jsp")
+[[ -z "${MYNET}" ]] && { echo "MYIP not found, maybe bad connectivity to alimonitor?" && exit 1; }
+
+## XROOTD Manager info
+MANAGER_HOST_PORT=$( /bin/awk -F": " '/seioDaemons/ { gsub ("root://","",$2); print $2 }' <<< "${se_info}" ) #'
+IFS=':' read -r -a mgr_host_port_arr <<< "${MANAGER_HOST_PORT}"
+MANAGERHOST="${mgr_host_port_arr[0]}"
+MANAGERPORT="${mgr_host_port_arr[1]}"
 
 ###############################################################################################
 ###   Network prerequisites for install
 
 ## Network information and validity checking
-MYNET=$(/usr/bin/curl -fsSLk http://alimonitor.cern.ch/services/ip.jsp)
-MYIP=$(echo "${MYNET}" | /bin/awk '/IP/ {gsub("IP:","",$1); print $1}')
-REVERSE=$(echo "${MYNET}" | /bin/awk '/FQDN/ {gsub("FQDN:","",$1); print $1}')
+MYIP=$(/bin/awk '/IP/ {gsub("IP:","",$1); print $1;}'  <<< "${MYNET}") #'
+REVERSE=$(/bin/awk '/FQDN/ {gsub("FQDN:","",$1); print $1;}'  <<< "${MYNET}" ) #'
 
 ## make sure the exit public ip is locally configured
-ip_list=$(/sbin/ip addr show scope global permanent up | /bin/awk '/inet/ {split ($2,ip,"/"); print ip[1]}')
-found_at=$(expr index "${ip_list}" "$MYIP")
-[[ "${found_at}" == "0" ]] && { echo "Server without public/rutable ip. No NAT schema supported at this moment" && exit 10; }
+ip_list=$(/sbin/ip addr show scope global permanent up | /bin/awk '/inet/ {split ($2,ip,"/"); print ip[1];}') #'
+found_at=$(expr index "${ip_list}" "${MYIP}")
+[[ "${found_at}" == "0" ]] && { echo "Server without public/rutable ip. No NAT schema supported at this moment"; exit 1; }
 
 ## what is my local set hostname
 [[ -z "${myhost}" ]] && myhost=$(/bin/hostname -f)
 [[ -z "${myhost}" ]] && myhost=$(/bin/hostname)
-[[ -z "${myhost}" ]] && echo "Cannot determine hostname. Aborting." && exit 1
+[[ -z "${myhost}" ]] && { echo "Cannot determine hostname. Aborting."; exit 1; }
 
 ## make sure the locally configured hostname is the same with the external one
-[[ "${myhost}" != "${REVERSE}" ]] && { echo "detected hostname $myhost does not corespond to reverse dns name $REVERSE" && exit 10; }
+[[ "${myhost}" != "${REVERSE}" ]] && { echo "detected hostname ${myhost} does not corespond to reverse dns name ${REVERSE}"; exit 1; }
 echo "The fully qualified hostname appears to be ${myhost}"
 
 ###############################################################################################
-###############################################################################################
-## INFORMATION ON THE SITE- based on MonaLisa information
-
-## Find information about site from ML
-
-## Find information about site from ML
-MONALISA_IP=$(/usr/bin/curl -s http://alimonitor.cern.ch/services/getClosestSite.jsp?ml_ip=true | /bin/awk -F, '{print $1}')
-MONALISA_FQDN=$(/usr/bin/host -t A ${MONALISA_IP} | /bin/awk '{ print substr ($NF,1,length($NF)-1);}')
-MONALISA_PORT="8884"
-
-ML_DEST="${MONALISA_FQDN}:${MONALISA_PORT}"
-
-## WHAT IS MY ROLE? ; we are interested only if i am manager
+## WHAT IS MY ROLE?
 is_manager=""
 ROLE="server"
 
 ## am i the top manager defined in ML ?
 ## maybe the manager is an alias to multiple redundant ips
-MANAGER_IP_LIST=$(host -t A ${MANAGERHOST} | awk '{print $NF;}')
+DNS_QUERY_IPv4=$(host -t A ${MANAGERHOST})
+DNS_QUERY_IPv6=$(host -t AAAA ${MANAGERHOST})
+
+[[ "${DNS_QUERY_IPv4}" =~ no.+record ]] || [[ "${DNS_QUERY_IPv4}" =~ NXDOMAIN ]] && DNS_QUERY_IPv4=""
+[[ "${DNS_QUERY_IPv6}" =~ no.+record ]] || [[ "${DNS_QUERY_IPv6}" =~ NXDOMAIN ]] && DNS_QUERY_IPv6=""
+
+MANAGER_IP_LIST=$(/bin/awk '{print $NF;}' <<< "${DNS_QUERY_IPv4}") #'
+MANAGER_IPv6_LIST=$(/bin/awk '{print $NF;}'  <<< "${DNS_QUERY_IPv6}") #'
 
 if (( $(echo ${MANAGER_IP_LIST} | wc -l) > 1 )) ; then
     ## is my ip in manager ip list
@@ -111,12 +119,15 @@ fi
 ## maybe i am a second tier manager?
 if [[ -z "${is_manager}" ]]; then
     ## have the ports of possible xrootd servers running; to be used to query the servers
-    XRD_PORT=$(ss -ltnp | awk '/xrootd/ { n=split($4,listening,":");print listening[n];}')
+    XRD_PORT=$(ss -ltnp | awk '/xrootd/ { n=split($4,listening,":");print listening[n];}') #'
 
     ## if ports (multiple servers possible) we query all to check if one is manager
-    for PORT in "${XRD_PORT}"; do
-        [[ -z "${is_manager}" ]] && ROLE=$(/usr/bin/xrdfs localhost:${PORT} query config role | tr -d '[:space:]'); [[ "${ROLE}" == "manager" ]] && is_manager="1" ;
-    done
+    if [[ -n "${XRD_PORT}" ]]; then
+      for PORT in ${XRD_PORT}; do
+          ROLE=$(/usr/bin/xrdfs localhost:${PORT} query config role | tr -d '[:space:]');
+          [[ "${ROLE}" == "manager" ]] && is_manager="1";
+      done
+    fi ## end check if xrd port found
 fi
 
 #########################################
@@ -144,14 +155,13 @@ echo "# Change this to the full path to xrd if it cannot be found in PATH, and r
 echo "lia.Monitor.modules.monXrdSpace.args=xrd ${MANAGERPORT}"
 ) >> ${CFG}
 
-if [[ "${is_manager}" == "1" ]] ; then
-    (
-    echo
-    echo "# Monitor xrootd disk space usage"
-    echo "# ************* IMPORTANT: only enable the following line on the redirector itself"
-    echo "mlsensor.modules=monXrdSpace"
-    ) >> ${CFG}
-fi
+# add monitoring of space
+(
+echo
+echo "# Monitor xrootd disk space usage"
+echo "# ************* IMPORTANT: only enable the following line on the redirector itself"
+echo "mlsensor.modules=monXrdSpace"
+) >> ${CFG}
 
 echo "!!!!!!! CHECK MLSensor ${CFG} to be sure that settings are ok!!!!!!!!!!!!"
 
